name: Publish Package to GitHub NPM Registry

on: 
  release: 
    types: published
    
jobs:
    npm-package:
      runs-on: ubuntu-latest
      permissions: 
        packages: write
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Install/set up NodeJS
          uses: actions/setup-node@v4
          with:
            node-version: 20.x
            registry-url: 'https://npm.pkg.github.com/'

        - name: install npm dependencies
          run: npm install

        - name: publish package
          run: npm publish
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}